# Generated by Django 4.1.2 on 2023-04-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0002_category_user_dailypurchase_user_payment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailypurchase',
            old_name='user',
            new_name='purchaseuser',
        ),
    ]
