# Generated by Django 4.1.2 on 2023-04-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailypurchase', '0005_alter_dailypurchase_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypurchase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailypurchase.category'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailypurchase.payment'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='suppliers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailypurchase.supplier'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
