# Generated by Django 4.1.2 on 2023-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0006_alter_dailypurchase_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
    ]
