# Generated by Django 5.1.2 on 2025-04-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypurchase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dailypurchase.category'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dailypurchase.payment'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='suppliers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dailypurchase.supplier'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
