# Generated by Django 5.1.2 on 2025-04-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0002_alter_dailypurchase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dailypurchase.category'),
        ),
    ]
