# Generated by Django 4.1.2 on 2023-04-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0003_rename_user_dailypurchase_purchaseuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailypurchase',
            old_name='purchaseuser',
            new_name='user',
        ),
    ]
