# Generated by Django 4.1.2 on 2023-04-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypurchase', '0004_rename_purchaseuser_dailypurchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypurchase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dailypurchase.category'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='dailypurchase.payment'),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='dailypurchase.supplier'),
        ),
    ]
